table1_plotter = function(data){
  
  reactable(
    data,
    minRows = 15,
    defaultPageSize = 15,
    searchable  = TRUE,
    showSortable =T,
    language = reactableLang(
      searchPlaceholder = "Search by MSA or Region Name"
    ),
    columns = list(
      Name = colDef(minWidth = 150),
      Region = colDef(minWidth = 80,
                      style = list(borderRight = "1px solid #000000"),
                      headerStyle = list(borderRight = "1px solid #000000")),
      abs_diff = colDef(name = "Abs Dif",
                        minWidth = 60,
                        headerClass = "reactableMetricHeader",
                        align = 'center'),
      abs_ratio = colDef(name = "Rel Dif",
                         minWidth = 60,
                         headerClass = "reactableMetricHeader",
                         align = 'center'),
      abs_cv = colDef(name = "Coefficient of variation (CV)",
                      minWidth = 100,
                      headerClass = "reactableMetricHeader",
                      align = 'center'),
      abs_gini = colDef(name = "Gini Coefficient",
                        headerClass = "reactableMetricHeader",
                        align = 'center'),
      abs_mld = colDef(name = "Mean log deviation",
                       style = list(borderRight = "1px solid #000000"),
                       headerStyle = list(borderRight = "1px solid #000000"),
                       headerClass = "reactableMetricHeader",
                       align = 'center'),
      income_diff = colDef(name = "Abs Dif",
                           minWidth = 60,
                           headerClass = "reactableMetricHeader",
                           align = 'center'),
      income_ratio = colDef(name = "Rel Dif",
                            minWidth = 60,
                            headerClass = "reactableMetricHeader",
                            align = 'center'),
      income_sii = colDef(name = "Slope index of inequality (SII)",
                          minWidth = 120,
                          headerClass = "reactableMetricHeader",
                          align = 'center'),
      income_rii = colDef(name = "Relative index of inequality (RII)",
                          minWidth = 120,
                          headerClass = "reactableMetricHeader",
                          align = 'center',
                          style = list(borderRight = "1px solid #000000"),
                          headerStyle = list(borderRight = "1px solid #000000"))
    ),
    columnGroups = list(
      colGroup(name = "Life Expectancy Disparities", 
               headerClass = "reactableTopTierTitle",
               headerStyle =  "border-left: black solid 1px;",
               columns = c("abs_diff", "abs_ratio", "abs_cv","abs_gini","abs_mld")),
      colGroup(name = "Income-related Disparities", 
               headerClass = "reactableTopTierTitle", 
               columns = c("income_diff", "income_ratio","income_sii","income_rii"))
    ))
}
