
formatTable1Cell =JS("function(cellInfo) {return cellInfo.row[cellInfo.column.id + '_formatted']}")

table1_plotter = function(df_table1){
  min_width_scaler = 2.2
  width_2digit_rounding = 60*min_width_scaler
  width_3digit_rounding = 60*min_width_scaler
  width_5digit_rounding = 90*min_width_scaler
  df_table1 %>% 
    reactable(
      minRows = 10,
      defaultPageSize = 10,
      searchable  = TRUE,
      showSortable =T,
      language = reactableLang(
        searchPlaceholder = "Search by MSA or Region Name"
      ),
      columns = list(
        Name = colDef(minWidth = 200),
        total_pop  = colDef(name = "Population",
                            minWidth = 110,
                            format =colFormat(separators = T)),
        Region = colDef(minWidth = 80,
                        style = list(borderRight = "1px solid #c7c7c7"),
                        headerStyle = list(borderRight = "1px solid #c7c7c7")),
        abs_diff = colDef(name = "Abs Dif",
                          minWidth = width_2digit_rounding,
                          headerClass = "reactableMetricHeader",
                          align = 'center',
                          cell = formatTable1Cell ),
        abs_diff_formatted = colDef(show=F),
        abs_ratio = colDef(name = "Rel Dif",
                           minWidth = width_2digit_rounding,
                           headerClass = "reactableMetricHeader",
                           align = 'center',
                           cell = formatTable1Cell),
        abs_ratio_formatted = colDef(show=F),
        abs_cv = colDef(name = "Coefficient of variation (CV)",
                        minWidth = width_2digit_rounding,
                        headerClass = "reactableMetricHeader",
                        align = 'center',
                        cell = formatTable1Cell),
        abs_cv_formatted = colDef(show=F),
        abs_gini = colDef(name = "Gini Coefficient",
                          minWidth = width_2digit_rounding,
                          headerClass = "reactableMetricHeader",
                          align = 'center',
                          cell = formatTable1Cell),
        abs_gini_formatted = colDef(show=F),
        abs_mld = colDef(name = "Mean log deviation",
                         minWidth = width_5digit_rounding,
                         style = list(borderRight = "1px solid #c7c7c7"),
                         headerStyle = list(borderRight = "1px solid #c7c7c7"),
                         headerClass = "reactableMetricHeader",
                         align = 'center',
                         cell = formatTable1Cell),
        abs_mld_formatted = colDef(show=F),
        income_diff = colDef(name = "Abs Dif",
                             minWidth = width_2digit_rounding,
                             headerClass = "reactableMetricHeader",
                             align = 'center',
                             cell = formatTable1Cell),
        income_diff_formatted = colDef(show=F),
        income_ratio = colDef(name = "Rel Dif",
                              minWidth = width_2digit_rounding,
                              headerClass = "reactableMetricHeader",
                              align = 'center',
                              cell = formatTable1Cell),
        income_ratio_formatted = colDef(show=F),
        income_bgv = colDef(name = "Between Group Variance (BGV)",
                            minWidth = width_5digit_rounding,
                            headerClass = "reactableMetricHeader",
                            align = 'center',
                            cell = formatTable1Cell),
        income_bgv_formatted = colDef(show=F),
        income_sii = colDef(name = "Slope index of inequality (SII)",
                            minWidth = width_5digit_rounding,
                            headerClass = "reactableMetricHeader",
                            align = 'center',
                            cell = formatTable1Cell),
        income_sii_formatted = colDef(show=F),
        income_rii = colDef(name = "Relative index of inequality (RII)",
                            minWidth = width_5digit_rounding,
                            headerClass = "reactableMetricHeader",
                            align = 'center',
                            style = list(borderRight = "1px solid #c7c7c7"),
                            headerStyle = list(borderRight = "1px solid #c7c7c7"),
                            cell = formatTable1Cell),
        income_rii_formatted = colDef(show=F)
        
      ),
      columnGroups = list(
        colGroup(name = "Life Expectancy Disparities", 
                 headerClass = "reactableTopTierTitle reactableTopTierTitle1",
                 headerStyle =  "border-left: #c7c7c7 solid 1px;",
                 columns = c("abs_diff",  "abs_ratio", "abs_cv","abs_gini","abs_mld")),
        colGroup(name = "Income-related Disparities", 
                 headerClass = "reactableTopTierTitle reactableTopTierTitle2", 
                 columns = c("income_diff", "income_ratio","income_bgv","income_sii","income_rii"))
      ))
}
